### ISSUE TITLE
The client is failing for large files

### ISSUE THREAD

**Issue by troggy** [toniopelo/modbox#5]
I have working setup of the library in my project, which works fine for regular files. However, if I try to upload large movie file (3.5Gb or more) I get a `DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.` error in my browser console. Upload is not working.

The error happens here: 

https://github.com/toniopelo/modbox/blob/6e83cde0addbef14be9fbb50ae30a660a660ab38/packages/s3-uploads-client/src/manager.ts#L97-L99

I guess because File#arrayBuffer tries to read the whole file in memory.

I suggest to rewrite the code to read the file chunk by chunk (e.g. using `File#slice` or get the stream with `File#stream` and read chunk data from it sequentially)

**Comment by toniopelo** [comment]
You're right, this is totally the way to go. I'll check your PR (awesome :)).
